account_id = "c0d1c807e52fc7039f226779d98c7ad7"
name = "cloud-flare"
type = "esbuild"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./build",entry-point = "workers-site"}
compatibility_date = "2022-04-03"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
