# Theme config
router: false

style:
  primary_color: "#0097A7"
  accent_color: "#00838F"
  bg_color: "#eeeeee"
  hoverable: true

info:
  bg_image: /images/bg.png
  avatar: /images/avatar.png
  slogan: "自童年起，我便独自一人，照顾历代星辰。"
  sns:
    Twitter:
      link: https://twitter.com
      fa: 'fa-twitter'
    Facebook:
      link: https://facebook.com
      null_icon: true
    Github:
      link: https://github.com/Lo-que
      md: 'md-github'

# HTML head
head:
  favicon: /images/favicon.png
  high_res_favicon: /images/favicon.png
  apple_touch_icon: /images/favicon.png
  keywords: Lo-que, qudongqi, blog

# Search
search: true

# Post
post:
  entry_excerpt: 0
  random_pics: 44
  qr_code: true
  prism:
    theme: darcula
    line_number: true
  license:
    name: 'CC BY-NC-SA 4.0'
    link:  'https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh'
  word_count: true
  read_time: true
  donate:
    wechat:
      link: /img/avatar.png
      fa: 'fa-wechat'
    paypay:
      link: 'https://paypal.com'
      fa: 'fa-paypal'

share_menu:
  rss: true
  weibo: true
  twitter: true
  facebook: true
  googleplus: true
  linkedin: true
  qq: true
  telegram: true

# pages:
#   Test1:
#     link: "/friends"
#     type: 'internal'
#     md: "&#xe0ba;"
#   Test2:
#     link: "/apply-for-link"
#     type: 'internal'
#     fa: "fa-child"
#   Test3:
#     link: "/galleries"
#     type: 'internal'
#     md: "home"
#   Test4:
#     cascade: true
#     md: 'home'
#     pages:
#       TEST1:
#         link: "/myfriends"
#         type: 'internal'
#         md: "&#xe5ca;"
#       TEST2:
#         link: "/timeline"
#         type: 'internal'
#         md: "home"

# comment
comment:
    use:
    shortname:

# footer
footer:
  since: 2017
  ICP:
  image:
  last_updated: false

# Service Worker
service_worker:

# scss
node_sass:
  debug: false
  outputStyle: compressed
  precision: 5
  sourceComments: false

# Vendors
vendors:
  style_min_css:
  outdatedbrowser_min_js:
  js_min_js:
  custom_head:
  custom_js:
